/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualsRouteImport } from './routes/visuals'
import { Route as VideoRouteImport } from './routes/video'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchCardRouteImport } from './routes/launch-card'
import { Route as GenerationRouteImport } from './routes/generation'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPipelinesRouteImport } from './routes/admin.pipelines'
import { Route as AdminModelsRouteImport } from './routes/admin.models'
import { Route as AdminMlopsRouteImport } from './routes/admin.mlops'

const VisualsRoute = VisualsRouteImport.update({
  id: '/visuals',
  path: '/visuals',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchCardRoute = LaunchCardRouteImport.update({
  id: '/launch-card',
  path: '/launch-card',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerationRoute = GenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPipelinesRoute = AdminPipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMlopsRoute = AdminMlopsRouteImport.update({
  id: '/mlops',
  path: '/mlops',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/generation': typeof GenerationRoute
  '/launch-card': typeof LaunchCardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/video': typeof VideoRoute
  '/visuals': typeof VisualsRoute
  '/admin/mlops': typeof AdminMlopsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/pipelines': typeof AdminPipelinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generation': typeof GenerationRoute
  '/launch-card': typeof LaunchCardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/video': typeof VideoRoute
  '/visuals': typeof VisualsRoute
  '/admin/mlops': typeof AdminMlopsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/pipelines': typeof AdminPipelinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/generation': typeof GenerationRoute
  '/launch-card': typeof LaunchCardRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRoute
  '/pricing': typeof PricingRoute
  '/products': typeof ProductsRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/video': typeof VideoRoute
  '/visuals': typeof VisualsRoute
  '/admin/mlops': typeof AdminMlopsRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/pipelines': typeof AdminPipelinesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/generation'
    | '/launch-card'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/products'
    | '/settings'
    | '/upload'
    | '/video'
    | '/visuals'
    | '/admin/mlops'
    | '/admin/models'
    | '/admin/pipelines'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generation'
    | '/launch-card'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/products'
    | '/settings'
    | '/upload'
    | '/video'
    | '/visuals'
    | '/admin/mlops'
    | '/admin/models'
    | '/admin/pipelines'
    | '/admin/settings'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/generation'
    | '/launch-card'
    | '/login'
    | '/marketplace'
    | '/pricing'
    | '/products'
    | '/settings'
    | '/upload'
    | '/video'
    | '/visuals'
    | '/admin/mlops'
    | '/admin/models'
    | '/admin/pipelines'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  GenerationRoute: typeof GenerationRoute
  LaunchCardRoute: typeof LaunchCardRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRoute
  PricingRoute: typeof PricingRoute
  ProductsRoute: typeof ProductsRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  VideoRoute: typeof VideoRoute
  VisualsRoute: typeof VisualsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visuals': {
      id: '/visuals'
      path: '/visuals'
      fullPath: '/visuals'
      preLoaderRoute: typeof VisualsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch-card': {
      id: '/launch-card'
      path: '/launch-card'
      fullPath: '/launch-card'
      preLoaderRoute: typeof LaunchCardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generation': {
      id: '/generation'
      path: '/generation'
      fullPath: '/generation'
      preLoaderRoute: typeof GenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pipelines': {
      id: '/admin/pipelines'
      path: '/pipelines'
      fullPath: '/admin/pipelines'
      preLoaderRoute: typeof AdminPipelinesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mlops': {
      id: '/admin/mlops'
      path: '/mlops'
      fullPath: '/admin/mlops'
      preLoaderRoute: typeof AdminMlopsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMlopsRoute: typeof AdminMlopsRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminPipelinesRoute: typeof AdminPipelinesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMlopsRoute: AdminMlopsRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminPipelinesRoute: AdminPipelinesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  GenerationRoute: GenerationRoute,
  LaunchCardRoute: LaunchCardRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRoute,
  PricingRoute: PricingRoute,
  ProductsRoute: ProductsRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  VideoRoute: VideoRoute,
  VisualsRoute: VisualsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
